---
- hosts: app

  tasks: 
    - name: Play 1 - Task 2
      debug:
        msg: Play 1 - Task 2

    - name: include second task
      include_tasks: play1_task2.yml

    - name: import task
      import_tasks: play1_task3.yml

- import_playbook: play4.yml
...
