---
- hosts: web
 

  tasks:
    - name: Ansible Jinja2 if
      debug:
        msg: >
             {#if the hostname is app1, include a message -#}
             {% if ansible_hostname=="orc-app1" -%}
                 This is app1 VM
             {% elif ansible_hostname=="orc-app2" -%}
                This is app2 VM
             {% else -%}
                This is db VM
             {% endif %}

    - name: jinja2 if a variable is defined
      debug:
        msg: >
             {% if example_variable is defined -%}
                 The example_variable is defined
             {% else -%}
                 The example_variable is not defined
             {% endif %}
    - name: jinja2 for statement
      debug: 
        msg: >
            {% for entry in ansible_all_ipv4_addresses -%}
               The entry value is {{ loop.index }} = {{ entry }}
            {% endfor %}

    - name: jinja2 template
      template: 
        src: tmeplate.j2
        dest: "/tmp/{{ ansible_hostname }}_template.out"
        trim_block: true
...
